[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "custom-ds-cli"
version = "0.1.0"
description = "Custom Data Science Project Generator"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Your Name", email = "your.email@example.com" },
]
dependencies = [
    "click>=8.0.0",
    "cookiecutter>=2.1.0",
    "rich>=10.0.0",  # For better CLI formatting
    "packaging>=23.0",  # For version parsing
    "questionary>=2.0.0",  # For interactive CLI prompts
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "ruff>=0.1.0",
    "pre-commit>=3.0.0",
]

[project.scripts]
create-ds = "custom_ds_cli.cli:cli"

[tool.hatch.build.targets.wheel]
packages = ["src/custom_ds_cli"]

[tool.ruff]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "UP", # pyupgrade
    "N",  # pep8-naming
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
]
fix = true 